name: pydamage
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - click=7.0
  - numpy=1.17.5
  - pandas=1.0.0
  - pip=20.0.2
  - pysam=0.15.4
  - python=3.7.6
  - scipy=1.4.1
  - statsmodels=0.11.0
